dedicated is not part of the BackendStatus schema and would have never worked (#417)
Fixes build failures due to "qiskit_ibm_runtime.exceptions.IBMBackendApiProtocolError: "Unexpected return value received from the server when getting backend status: __init__() got an unexpected keyword argument 'dedicated'""